language: node_js
node_js: 
  - "4.1"
services: mongodb
before_script:
  - npm install -g gulp
script: 
  - node test/init/test-init.js
  - node lib/server/server.js &
  - gulp test
env:
  - NODE_ENV=test CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
